Global:
  use_amp: true
  use_gpu: true
  epoch_num: 300
  log_smooth_window: 50
  print_batch_step: 10
  save_model_dir: C:/Users/Aserr/Desktop/GitHub/469/zzz/data/output/rec_handwriting
  save_epoch_step: 5
  eval_batch_step: 1000
  evaluation_step: 500
  pretrained_model: C:/Users/Aserr/Desktop/GitHub/469/zzz/data/pretrain_models/rec_crnn/en_number_mobile_v2.0_rec_slim_train/best_accuracy.pdparams
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: PaddleOCR/ppocr/utils/dict/en_dict.txt
  max_text_length: 150
  infer_mode: false
  use_space_char: true
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
Architecture:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 1.0
    model_name: small
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 1.0e-05
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list:
    - ./train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size: 128
    batch_size_per_card: 128
    drop_last: true
    num_workers: 16
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list:
    - ./train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size: 128
    batch_size_per_card: 128
    num_workers: 4
profiler_options: null
